apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-servers
  namespace: database
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "Home Lab PostgreSQL",
          "Group": "Servers",
          "Host": "postgresql.database.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "myapp",
          "Username": "myapp",
          "SSLMode": "prefer"
        }
      }
    }
