apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-secrets
  namespace: argocd
  annotations:
    # Must be AFTER sealed-secrets (-10). Use -5 or 0.
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: https://github.com/BDomantas/home_cluster.git
    targetRevision: master
    path: clusters/base/argocd-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
