apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"

spec:
  project: default

  sources:
    - repoURL: oci://ghcr.io/prometheus-community/charts
      chart: kube-prometheus-stack
      targetRevision: 81.4.2
      helm:
        releaseName: monitoring
        valueFiles:
          - $values/platform/monitoring/values.yaml
          - $values/platform/monitoring/values-dev.yaml

    - repoURL: https://github.com/BDomantas/home_cluster.git
      targetRevision: master
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
