apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-netbird-test
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"

spec:
  project: default

  source:
    repoURL: https://github.com/BDomantas/home_cluster.git
    targetRevision: master
    path: platform/test/nginx

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
